- name: Restart php-fpm
  service:
    name: "{{ _php_service }}"
    state: restarted
  listen: restart-phpfpm
  when: php_fpm

- name: Restart apache
  service:
    name: "{{ _apache_service }}"
    state: restarted
  listen: restart-webserver
  when: _apache_role is defined

- name: Restart nginx
  service:
    name: "{{ _nginx_service }}"
    state: restarted
  listen: restart-webserver
  when: _nginx_role is defined